name: HyperTuner INI validate
description: GitHub Action for INI validation.
author: Piotr Rogowski <piotr.rogowski0@gmail.com>
branding:
  icon: cpu
  color: blue
inputs:
  github-token:
    description: GitHub token.
    required: true
  filename:
    description: Path to INI file.
    required: true

runs:
  using: composite
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
    - name: Validate
      shell: bash
      run: |
        NPM_GITHUB_TOKEN=${{ inputs.github-token }}
        echo -e "@hyper-tuner:registry=https://npm.pkg.github.com\n//npm.pkg.github.com/:_authToken=${NPM_GITHUB_TOKEN}" > .npmrc
        npx -y hyper-tuner/ini validate ${{ inputs.filename }}
